#!/bin/bash
set -euo pipefail

list_pkgs() {
  cat <<'EOF' | awk '/^[^#]/ { print $1 }'
atool
bash-completion
cpufrequtils
curl
dnsutils
fail2ban
fzf
gpm
haveged  # entropy FTW
htop
inotify-tools
iotop
lftp
ncdu
net-tools  # netstat
nmap
pwgen
ripgrep
rsync
sqlite3
tmux
tofrodos
tree
vim-nox
wajig
wamerican-huge
whois
wngerman
wogerman
EOF
}

set -x
sudo apt-get install -y $(list_pkgs)
