#!/bin/bash
set -euo pipefail

args=(
  atool
  bash-completion
  cpufrequtils
  curl
  dnsutils
  fail2ban
  gpm
  haveged  # entropy FTW
  htop
  inotify-tools
  iotop
  lftp
  ncdu
  net-tools  # netstat
  nmap
  pwgen
  ripgrep
  rsync
  sqlite3
  tmux
  tofrodos
  tree
  unzip
  vim-nox
  whois
)

set -x
sudo apt-get install -y ${args[@]}
