#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

# https://grafana.com/docs/alloy/latest/set-up/install/linux/
sudo -i <<'ENDOFSUDO'
apt-get update
apt-get -y install gpg
sudo mkdir -p /etc/apt/keyrings/
wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor > /etc/apt/keyrings/grafana.gpg
echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" > /etc/apt/sources.list.d/grafana.list

apt-get update
apt-get -y install alloy
ENDOFSUDO
