#!/bin/bash
set -euo pipefail

finally() {
  rm /tmp/awscliv2.zip
  rm -r /tmp/aws
}
trap finally EXIT

cd /tmp
curl -sS "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip -q awscliv2.zip
sudo ./aws/install
