#!/bin/bash
set -euo pipefail

# https://borgbackup.readthedocs.io/en/stable/installation.html
sudo add-apt-repository -y ppa:costamagnagianfranco/borgbackup
sudo apt-get update
sudo apt-get install -y borgbackup

