#!/bin/bash
set -euo pipefail

# https://sites.google.com/chromium.org/driver/
cd /tmp/
wget https://chromedriver.storage.googleapis.com/97.0.4692.71/chromedriver_linux64.zip
unzip chromedriver_linux64.zip 
chmod +x chromedriver
sudo mv chromedriver /usr/local/bin/
rm chromedriver_linux64.zip 
