#!/bin/bash
set -euo pipefail

BINDIR=~/.local/bin
mkdir -p $BINDIR

# https://github.com/bcicen/ctop/releases
wget https://github.com/bcicen/ctop/releases/download/v0.7.7/ctop-0.7.7-linux-amd64 -O $BINDIR/ctop
chmod +x $BINDIR/ctop
