#!/bin/bash
set -euo pipefail

# https://docs.docker.com/compose/install/other/
sudo curl -SsL https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose version
