#!/bin/bash
set -euo pipefail

set -x

distrib_id=$(lsb_release -is)
case $distrib_id in
  Debian)
    url=https://download.docker.com/linux/debian
    codename=$(lsb_release -cs)
    ;;
  Ubuntu)
    url=https://download.docker.com/linux/ubuntu
    codename=$(lsb_release -cs)
    ;;
  Linuxmint)
    url=https://download.docker.com/linux/ubuntu
    # \K: Tells grep to "forget" everything matched so far, effectively starting the match after UBUNTU_CODENAME=.
    codename=$(grep -oP '^UBUNTU_CODENAME=\K.*' /etc/os-release)
esac

# https://docs.docker.com/engine/install/debian/
# https://docs.docker.com/engine/install/ubuntu/
sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] $url \
  $codename stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io
