#!/bin/bash
set -euo pipefail

old="$PWD"
home=${HOME:-/root}
username=${USER:-root}

cd $home
git clone https://github.com/felixhummel/configs.git
cd configs
./init --force --email "$username@$(hostname -f)" --name "$username"

cd "$old"

exec $SHELL
