#!/bin/bash
set -euo pipefail

old="$PWD"

cd ${HOME:-/root}
git clone https://github.com/felixhummel/configs.git
cd configs
./init --force --email "$USER@$(hostname -f)" --name "$USER"

cd "$old"

exec $SHELL
