#!/bin/bash
set -euo pipefail

if [[ -d ~/.fzf ]]; then
  echo "already present: ~/.fzf"
  exit 1
fi

# https://github.com/junegunn/fzf#using-git
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
