#!/bin/bash
set -euo pipefail

# https://github.com/junegunn/fzf#using-git
if [[ ! -d ~/.fzf ]]; then
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
else
  cd ~/.fzf
  echo "CURRENT: $(git rev-parse HEAD)" >&2
  git pull --ff-only
fi
~/.fzf/install --key-bindings --completion --no-update-rc
