#!/bin/bash
set -euo pipefail

cd /tmp/
# https://crates.io/crates/git-find
# https://github.com/davidb/git-find/releases
wget https://github.com/davidB/git-find/releases/download/0.5.0/git-find_0.5.0-x86_64-unknown-linux-gnu.tar.gz
tar xf git-find*.tar.gz 
rm git-find*.tar.gz 
sudo mv git-find /usr/local/bin/
