#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

# https://go.dev/dl/
sudo -i <<'ENDOFSUDO'
cd /tmp
wget https://go.dev/dl/go1.23.4.linux-amd64.tar.gz
rm -rf /usr/local/go && tar -C /usr/local -xzf go1.23.4.linux-amd64.tar.gz
ENDOFSUDO
