#!/bin/bash
set -euo pipefail

sudo -i <<'ENDOFSUDO'
apt build-dep gource

cd /tmp/
wget -c https://github.com/acaudwell/Gource/releases/download/gource-0.54/gource-0.54.tar.gz
tar xf gource-0.54.tar.gz

cd /tmp/gource-0.54/
cores=$(( $(nproc) - 1 ))
./configure && make -j $cores && make install
cd $HOME

rm -r /tmp/gource-0.54/
ENDOFSUDO
