#!/bin/bash
set -euo pipefail

set -x
cd /tmp
wget https://get.helm.sh/helm-v3.4.1-linux-amd64.tar.gz
tar xf helm-v3.4.1-linux-amd64.tar.gz
sudo mv linux-amd64/helm /usr/local/bin/helm
rm -r linux-amd64
