#!/bin/bash
set -euo pipefail

version=${1:-}

if [[ -z $version ]]; then
  version=$(curl -L -s https://dl.k8s.io/release/stable.txt)
fi
mkdir -p ~/.local/bin/
cd ~/.local/bin/
curl -LO "https://dl.k8s.io/release/${version}/bin/linux/amd64/kubectl"
chmod +x kubectl
