#!/bin/bash
set -euo pipefail

mkdir -p ~/.local/bin/
cd ~/.local/bin/
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
chmod +x kubectl
