#!/bin/bash
set -euo pipefail

# https://github.com/grafana/loki/releases /logcli
cd /tmp
wget -cq https://github.com/grafana/loki/releases/download/v2.7.4/logcli-linux-amd64.zip
unzip -q logcli-linux-amd64.zip
rm logcli-linux-amd64.zip
sudo mv logcli-linux-amd64 /usr/local/bin/logcli
