#!/bin/bash
set -euo pipefail

cd /tmp/
wget https://github.com/axllent/mailpit/releases/download/v1.4.0/mailpit-linux-amd64.tar.gz
tar xf mailpit-linux-amd64.tar.gz mailpit
rm mailpit-linux-amd64.tar.gz
sudo mv mailpit /usr/local/bin/mailpit
# mailpit --smtp 127.0.0.1:1025 --listen 127.0.0.1:1080
