#!/bin/bash
set -euo pipefail

sudo apt-get -y install libolm-dev
pipx install matrix-commander


# check element for room id via "copy invite link", e.g. !xxxxxxxxxxxxxxxxxx:matrix.org
# matrix-commander --login password
# matrix-commander --verify
