#!/bin/bash
set -euo pipefail


wget https://github.com/neovim/neovim/releases/download/stable/nvim.appimage -O ~/.local/bin/nvim
chmod +x ~/.local/bin/nvim

cd /tmp
~/.local/bin/nvim --appimage-extract nvim.desktop
cp squashfs-root/nvim.desktop ~/.local/share/applications/
~/.local/bin/nvim --appimage-extract usr/share/icons/hicolor/128x128/apps/nvim.png
rsync -a squashfs-root/usr/share/icons/ /home/felix/.local/share/icons/
