#!/bin/bash
set -euo pipefail


wget https://github.com/neovim/neovim/releases/download/stable/nvim.appimage -O /usr/local/bin/nvim
chmod +x /usr/local/bin/nvim

cd /tmp
/usr/local/bin/nvim --appimage-extract nvim.desktop
mkdir -p /usr/local/share/applications/
cp squashfs-root/nvim.desktop /usr/local/share/applications/
/usr/local/bin/nvim --appimage-extract usr/share/icons/hicolor/128x128/apps/nvim.png
mkdir -p /usr/share/icons/
rsync -a squashfs-root/usr/share/icons/ /usr/share/icons/
rm -r /tmp/squashfs-root/
