#!/bin/bash
set -euo pipefail


sudo -i <<'ENDOFSUDO'
wget https://github.com/neovim/neovim/releases/download/v0.11.0/nvim-linux-x86_64.appimage -O /usr/local/bin/nvim
chmod +x /usr/local/bin/nvim

cd /tmp
/usr/local/bin/nvim --appimage-extract nvim.desktop
mkdir -p /usr/local/share/applications/
desktop-file-install squashfs-root/nvim.desktop
/usr/local/bin/nvim --appimage-extract usr/share/icons/hicolor/128x128/apps/nvim.png
mkdir -p /usr/share/icons/
rsync -a squashfs-root/usr/share/icons/ /usr/share/icons/
rm -r /tmp/squashfs-root/
ENDOFSUDO
