#!/bin/bash
set -euo pipefail

# https://prometheus.io/docs/guides/node-exporter/
cd /tmp

wget -cq https://github.com/prometheus/node_exporter/releases/download/v1.9.1/node_exporter-1.9.1.linux-amd64.tar.gz

tar xf node_exporter-*.*-amd64.tar.gz
rm node_exporter-*.*-amd64.tar.gz

sudo mv node_exporter-*.*-amd64/node_exporter /usr/local/bin/
rm -r node_exporter-*.*-amd64

# systemd files based on
# https://github.com/prometheus/node_exporter/tree/master/examples/systemd
sudo -i <<'ENDOFSUDO'
cat <<'EOF' > /etc/systemd/system/node_exporter.socket
[Unit]
Description=Node Exporter

[Socket]
ListenStream=9100

[Install]
WantedBy=sockets.target
EOF

cat <<'EOF' > /etc/systemd/system/node_exporter.service
[Unit]
Description=Node Exporter
Requires=node_exporter.socket

[Service]
DynamicUser=yes
ExecStart=/usr/local/bin/node_exporter --web.systemd-socket

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now node_exporter
ENDOFSUDO
