#!/bin/bash
set -euo pipefail

cd /tmp/
wget -qc https://github.com/grafana/loki/releases/download/v2.7.3/promtail-linux-amd64.zip
unzip -q promtail-linux-amd64.zip
rm promtail-linux-amd64.zip
sudo mv promtail-linux-amd64 /usr/local/bin/promtail
sudo chmod +x /usr/local/bin/promtail
