#!/bin/bash
set -euo pipefail

# https://github.com/pyenv/pyenv/wiki/common-build-problems
pkgs="
build-essential
curl
git
libbz2-dev
libffi-dev
liblzma-dev
libncurses5-dev
libncursesw5-dev
libreadline-dev
libsqlite3-dev
libssl-dev
llvm
make
python3-openssl
tk-dev
wget
xz-utils
zlib1g-dev
"

set -x
sudo apt-get install -y $pkgs

# https://github.com/pyenv/pyenv
git clone https://github.com/pyenv/pyenv.git ~/.pyenv
# https://github.com/pyenv/pyenv-virtualenv
git clone https://github.com/pyenv/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv
