#!/bin/bash
set -euo pipefail

# https://github.com/phiresky/ripgrep-all
apt install ripgrep pandoc poppler-utils ffmpeg

# https://github.com/phiresky/ripgrep-all/releases
cd /tmp
wget https://github.com/phiresky/ripgrep-all/releases/download/v0.9.6/ripgrep_all-v0.9.6-x86_64-unknown-linux-musl.tar.gz
tar xf ripgrep_all-v0.9.6-x86_64-unknown-linux-musl.tar.gz

mkdir -p ~/.local/bin
mv ripgrep_all-v0.9.6-x86_64-unknown-linux-musl/rga ~/.local/bin/
chmod +x ~/.local/bin/rga
