#!/bin/bash
set -euo pipefail

# https://help.seafile.com/syncing_client/install_linux_client/
set -x
sudo wget https://linux-clients.seafile.com/seafile.asc -O /usr/share/keyrings/seafile-keyring.asc
sudo bash -c "echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/seafile-keyring.asc] https://linux-clients.seafile.com/seafile-deb/focal/ stable main' > /etc/apt/sources.list.d/seafile.list"
sudo apt-get update && sudo apt-get install -y seafile-gui seafile-cli
