#!/bin/bash
set -euo pipefail

# https://smallstep.com/docs/step-cli/installation
cd /tmp
wget https://dl.smallstep.com/gh-release/cli/docs-cli-install/v0.24.4/step-cli_0.24.4_amd64.deb
sudo dpkg -i step-cli_*_amd64.deb
rm step-cli_*_amd64.deb
