#!/bin/bash
set -euo pipefail

# https://github.com/warrensbox/terraform-switcher/releases
cd /tmp/
wget -cq "https://github.com/warrensbox/terraform-switcher/releases/download/v1.1.1/terraform-switcher_v1.1.1_linux_amd64.tar.gz"
tar xf terraform-switcher_*.tar.gz

mkdir -p ~/.local/bin/
mv tfswitch ~/.local/bin/

rm terraform-switcher_*.tar.gz
