#!/bin/bash
set -euo pipefail

sudo -i <<'ENDOFSUDO'
addgroup --gid 1337 felix
adduser --uid 1337 --gid 1337 --gecos 'Felix Hummel' felix
for g in adm cdrom sudo dip plugdev lpadmin lxd sambashare libvirt; do
  adduser felix $g
done
ENDOFSUDO
