#!/bin/bash
set -euo pipefail

# https://github.com/mikefarah/yq/releases
VERSION=v4.34.2
BINARY=yq_linux_amd64
sudo wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/local/bin/yq \
  && sudo chmod +x /usr/local/bin/yq
