#!/bin/bash
set -euo pipefail

cd /tmp
# https://github.com/zellij-org/zellij/releases
wget -qc https://github.com/zellij-org/zellij/releases/download/v0.39.2/zellij-x86_64-unknown-linux-musl.tar.gz
tar xf zellij-x86_64-unknown-linux-musl.tar.gz
mv zellij ~/.local/bin
rm zellij-x86_64-unknown-linux-musl.tar.gz
