#!/bin/bash
set -euo pipefail

# Curl had a bug that resulted in spam when the -v flag was given, e.g.
#     * Expire in 1 ms for 1 (transfer 0x55bf226f5c10)
# Install curl from backports
# https://backports.debian.org/Instructions/
# hetzner:
# deb http://mirror.hetzner.de/debian/packages buster-backports main
set -x
[[ $UID == 0 ]]
if ! egrep -q ^deb.+buster-backports /etc/apt/sources.list; then
  echo 'deb http://deb.debian.org/debian buster-backports main' >> /etc/apt/sources.list
fi

apt-get install -y curl/buster-backports
