#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

sudo -i <<'ENDOFSUDO'
sed -i.bak -e 's/.*ClassicBondedOnly=.*/ClassicBondedOnly=false/' /etc/bluetooth/input.conf
systemctl restart bluetooth
ENDOFSUDO

