#!/bin/bash
set -euo pipefail

sudo -i <<'ENDOFSUDO'
git init /etc/fail2ban
cd /etc/fail2ban
git add .
git commit -m 'initial'

cat <<'EOF' > jail.local
[sshd]
maxretry = 1
bantime  = 4h
EOF

git add jail.local
git commit -m 'sshd jail stricter'

systemctl restart fail2ban
ENDOFSUDO
