#!/bin/bash
set -euo pipefail

# silence this:
#
# rtkit-daemon[1331]: Supervising 9 threads of 6 processes of 1 users.
# rtkit-daemon[1331]: message repeated 7 times: [ Supervising 9 threads of 6 processes of 1 users.]
#
# Thanks to MC68020 for https://unix.stackexchange.com/a/686283
sudo -i <<'ENDOFSUDO'
install -d -m 755 /etc/systemd/system/rtkit-daemon.service.d

cat <<'EOF' > /etc/systemd/system/rtkit-daemon.service.d/log.conf
[Service]
LogLevelMax=5
EOF

systemctl daemon-reload
systemctl restart rtkit-daemon.service
ENDOFSUDO
