#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

# https://www.reddit.com/r/Nix/comments/1fwdzla/comment/lrqpdsk/
cat <<'EOF' > ~/.bash/mise-completion
# Backwards compatibility for compat completions that use have().
# @deprecated should no longer be used; generally not needed with dynamically
#             loaded completions, and _have is suitable for runtime use.
have()
{
    unset -v have
    _have $1 && have=yes
}
EOF
mise completion bash --include-bash-completion-lib >> ~/.bash/mise-completion
