#!/bin/bash
set -euo pipefail

cd /tmp
# https://github.com/jgraph/drawio-desktop/releases
wget -c https://github.com/jgraph/drawio-desktop/releases/download/v22.0.2/drawio-amd64-22.0.2.deb
sudo dpkg -i drawio-amd64-*.deb
rm drawio-amd64-*.deb
