#!/bin/bash
set -euo pipefail

sudo -i <<'ENDOFSUDO'
wget -q https://dl-ssl.google.com/linux/linux_signing_key.pub -O - | gpg --dearmor > /usr/share/keyrings/google-chrome.gpg

cat <<'EOF' > /etc/apt/sources.list.d/google-chrome.list
deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main
EOF

apt-get update
apt-get -y install google-chrome-stable
ENDOFSUDO

