#!/bin/bash
set -euo pipefail

set -x
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo -i <<'ENDOFSUDO'
cat <<'EOF' > /etc/apt/sources.list.d/google-chrome.list
deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
EOF

apt-get update
apt-get -y install google-chrome-stable
ENDOFSUDO

