#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

sudo apt-get build-dep gource

cd /tmp
wget https://github.com/acaudwell/Gource/releases/download/gource-0.54/gource-0.54.tar.gz
tar xf gource-0.54.tar.gz
rm gource-0.54.tar.gz
cd gource-0.54/
./configure && make && sudo make install
