#!/bin/bash
set -euo pipefail

BINDIR=$HOME/.local/bin
mkdir -p $BINDIR

bin=$BINDIR/greenclip
wget -qc https://github.com/erebe/greenclip/releases/download/v4.2/greenclip -O $bin
chmod +x $bin
echo $bin >&2

cat <<EOF > ~/.config/greenclip.toml
[greenclip]
blacklisted_applications = []
enable_image_support = true
history_file = "$HOME/.cache/greenclip.history"
image_cache_directory = "/tmp/greenclip"
max_history_length = 50
max_selection_size_bytes = 0
static_history = []
trim_space_from_selection = true
use_primary_selection_as_input = true
EOF

cat <<EOF > ~/.config/autostart/greenclip.desktop
[Desktop Entry]
Encoding=UTF-8
Version=0.9.4
Type=Application
Name=greenclip
Comment=
Exec=$HOME/.local/bin/greenclip daemon
OnlyShowIn=XFCE;
RunHook=0
StartupNotify=false
Terminal=false
Hidden=false
EOF

cat <<EOF >&2
rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'
EOF
