#!/bin/bash
set -euo pipefail

mkdir -p ~/apps
cd ~/apps/
wget -qc https://github.com/LMMS/lmms/releases/download/v1.2.2/lmms-1.2.2-linux-x86_64.AppImage
chmod +x lmms-1.2.2-linux-x86_64.AppImage

cd /tmp
~/apps/lmms-1.2.2-linux-x86_64.AppImage --appimage-extract lmms.desktop  # for future reference
cat <<EOF > ~/.local/share/applications/lmms.desktop
[Desktop Entry]
Name=LMMS
Icon=lmms
Exec=$HOME/apps/lmms-1.2.2-linux-x86_64.AppImage
Terminal=false
Type=Application
Categories=Qt;AudioVideo;Audio;Midi;
MimeType=application/x-lmms-project;
EOF

~/apps/lmms-1.2.2-linux-x86_64.AppImage --appimage-extract lmms.png
mv squashfs-root/lmms.png ~/.local/share/icons/

rm -r /tmp/squashfs-root/
