#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

cd /tmp
sudo apt-get install -y vulkan-tools
wget -c https://github.com/lutris/lutris/releases/download/v0.5.17/lutris_0.5.17_all.deb
sudo dpkg -i lutris_0.5.17_all.deb
rm lutris*.deb
