#!/bin/bash
set -euo pipefail

cd /tmp

# https://mpv.io/installation/
# https://fruit.je/apt
# https://apt.fruit.je/
[[ -f /etc/os-release ]] && source /etc/os-release || UBUNTU_CODENAME=$(lsb_release -cs)
sudo -i <<ENDOFSUDO
curl --output-dir /etc/apt/trusted.gpg.d -O https://apt.fruit.je/fruit.gpg
cat <<EOF > /etc/apt/sources.list.d/fruit.list
deb http://apt.fruit.je/ubuntu $UBUNTU_CODENAME mpv
EOF

apt-get update
apt-get install -y mpv-fruit
ENDOFSUDO


# MPRIS D-Bus interface to integrate with https://github.com/felixhummel/bin/blob/master/music
mkdir -p ~/.config/mpv/scripts/
wget -qc https://github.com/hoyon/mpv-mpris/releases/download/1.0/mpris.so -O ~/.config/mpv/scripts/mpris.so

# Usage Example:
# mpv --no-video --vo=null --ytdl-format='bestaudio/best' 'https://example.com/watch?some-video'
