#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

cd /tmp
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/UbuntuMono.zip
unzip UbuntuMono.zip

mkdir -p ~/.fonts
cp UbuntuMonoNerdFontMono-Regular.ttf ~/.fonts/
fc-cache -f
