#!/bin/bash
set -euo pipefail

# https://obsproject.com/wiki/install-instructions#ubuntumint-installation
sudo add-apt-repository -y ppa:obsproject/obs-studio
sudo apt-get -y install ffmpeg v4l2loopback-dkms obs-studio
