#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

# https://github.com/fdw/rofimoji/
uv tool install rofimoji
cat <<'EOF' >~/.config/rofimoji.rc
action = copy
files = [emojis]
skin-tone = neutral
EOF
