#!/bin/bash
set -euo pipefail

# https://help.seafile.com/syncing_client/install_linux_client/
set -x
[[ -f /etc/os-release ]] && source /etc/os-release || UBUNTU_CODENAME=$(lsb_release -cs)

sudo wget https://linux-clients.seafile.com/seafile.asc -O /usr/share/keyrings/seafile-keyring.asc
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/seafile-keyring.asc] https://linux-clients.seafile.com/seafile-deb/$UBUNTU_CODENAME/ stable main" | sudo tee /etc/apt/sources.list.d/seafile.list > /dev/null
sudo apt-get update && sudo apt-get install -y seafile-gui seafile-cli

mkdir -p ~/.config/autostart
cd ~/.config/autostart
ln -s /usr/share/applications/seafile.desktop
