#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

args=(
  # xprop
  # xwininfo
  x11-utils
  xdotool
  # xrandr
  x11-xserver-utils
)

set -x
sudo apt-get install -y "${args[@]}"

mkdir -p ~/github
cd ~/github
git clone https://github.com/noctuid/tdrop.git
cd tdrop
sudo make install
